export default [{
  name: '总览',
  icon: '',
  id: 1,
  children: [{
    name: '总揽',
    icon: '',
    path: '/survey'
  }, {
    name: '总体概览',
    icon: '',
    path: ''
  }, {
    name: '工作台',
    icon: '',
    path: ''
  }, {
    name: '驾驶舱',
    icon: '',
    path: ''
  }, {
    name: '自定义报表',
    icon: '',
    path: ''
  }, {
    name: '客户概览',
    icon: '',
    path: ''
  }, {
    name: '产品概览',
    icon: '',
    path: ''
  }, {
    name: '销售概览',
    icon: '',
    path: ''
  }, {
    name: '营销概览',
    icon: '',
    path: ''
  }, {
    name: '生产概览',
    icon: '',
    path: ''
  }, {
    name: '业务概览',
    icon: '',
    path: ''
  }, {
    name: '运营概览',
    icon: '',
    path: ''
  }, {
    name: '管理概览',
    icon: '',
    path: ''
  }, {
    name: '生态概览',
    icon: '',
    path: ''
  }]
}, {
  name: '客户',
  icon: '',
  id: 2,
  children: [{
    name: '客户管理',
    icon: '',
    path: '/allCustoms'
  }, {
    name: '客户概览',
    icon: '',
    path: ''
  }, {
    name: '用户管理',
    icon: '',
    path: ''
  }, {
    name: '会员管理',
    icon: '',
    path: ''
  }, {
    name: '客户服务',
    icon: '',
    path: ''
  }, {
    name: '售后服务',
    icon: '',
    path: ''
  }]
}, {
  name: '产品',
  icon: '',
  id: 3,
  width: 280,
  children: [{
    name: '产品管理',
    icon: '',
    path: '/listOfUnit'
  }, {
    name: '商品管理',
    icon: '',
    path: '/commodity/conventionalKnowledge'
  }, {
    name: '库存管理',
    icon: '',
    path: '/storeInventory'
  }, {
    name: '产品概览',
    icon: '',
    path: ''
  }, {
    name: '产品分类',
    icon: '',
    path: ''
  }, {
    name: '产品定价',
    icon: '',
    path: ''
  }, {
    name: '进货管理',
    icon: '',
    path: ''
  }, {
    name: '产品仓库',
    icon: '',
    path: ''
  }, {
    name: '上架商品',
    icon: '',
    path: ''
  }, {
    name: '渠道铺货（小程序、微商城、线下货架等）',
    icon: '',
    path: ''
  }]
}, {
  name: '销售',
  icon: '',
  id: 4,
  width: 280,
  children: [{
    name: '渠道管理',
    icon: '',
    path: '/customMenu'
  }, {
    name: '商品订单',
    icon: '',
    path: '/allOrders'
  }, {
    name: '订单管理',
    icon: '',
    path: '/transactionManagement/magazineManagement'
  }, {
    name: '销售概览',
    icon: '',
    path: ''
  }, {
    name: '商机管理',
    icon: '',
    path: ''
  }, {
    name: '分销管理',
    icon: '',
    path: ''
  }, {
    name: '自销管理',
    icon: '',
    path: ''
  }, {
    name: '代销管理',
    icon: '',
    path: ''
  }, {
    name: '零售终端',
    icon: '',
    path: ''
  }, {
    name: '退换货',
    icon: '',
    path: ''
  }, {
    name: '销售渠道（第三方销售平台，如美团、饿了么、淘宝、天猫、美城茂等销售渠道管理）',
    icon: '',
    path: ''
  }]
}, {
  name: '营销',
  icon: '',
  id: 5,
  children: [{
    name: '营销应用',
    icon: '',
    path: '/marketingCenter',
  }, {
    name: '礼券管理',
    icon: '',
    path: '',
    children: [{
      name: '优惠券管理 ',
      icon: '',
      path: ''
    }, {
      name: '礼券管理 ',
      icon: '',
      path: ''
    }, {
      name: '代金券管理 ',
      icon: '',
      path: ''
    }]
  }, {
    name: '营销助手',
    icon: '',
    path: '',
    children: [{
      name: '营销助手',
      icon: '',
      path: '/marketingManagement/couponManagement'
    }, {
      name: '短信群发',
      icon: '',
      path: ''
    }, {
      name: '电子券群发',
      icon: '',
      path: ''
    }]
  }, {
    name: '促销中心',
    icon: '',
    path: '',
    children: [{
      name: '团购',
      icon: '',
      path: ''
    }, {
      name: '秒杀',
      icon: '',
      path: ''
    }, {
      name: '拼团',
      icon: '',
      path: ''
    }, {
      name: '拍卖',
      icon: '',
      path: ''
    }, {
      name: '返利',
      icon: '',
      path: ''
    }]
  }, {
    name: '推广中心',
    icon: '',
    path: '/toPromote/gather'
  }, {
    name: '营销活动',
    icon: '',
    path: ''
  }, {
    name: '智能公文',
    icon: '',
    path: ''
  }, {
    name: '内容营销',
    icon: '',
    path: ''
  }, {
    name: '全员任务',
    icon: '',
    path: ''
  }, {
    name: '营销案例',
    icon: '',
    path: ''
  }]
}, {
  name: '业务',
  icon: '',
  id: 6,
  width: 170,
  children: [{
    name: '采购',
    icon: '',
    path: ''
  }, {
    name: '供应链',
    icon: '',
    path: ''
  }, {
    name: '售后',
    icon: '',
    path: ''
  }, {
    name: '上下游合作等各类业务管理',
    icon: '',
    path: ''
  }, {
    name: '智能终端',
    icon: '',
    path: ''
  }, {
    name: '监控',
    icon: '',
    path: ''
  }, {
    name: '流程',
    icon: '',
    path: ''
  }]
}, {
  name: '运营',
  icon: '',
  id: 7,
  children: [{
    name: '门店运营',
    icon: '',
    path: '/storeList'
  }, {
    name: '系统设置',
    icon: '',
    path: '/businessInformation'
  }, {
    name: '商铺设置',
    icon: '',
    path: '/shopManagement/shopManagement'
  }, {
    name: '内容管理',
    icon: '',
    path: '/contentManagement/magazineManagement'
  }, {
    name: '运营监测',
    icon: '',
    path: '',
    children: [{
      name: '运监大屏',
      icon: '',
      path: ''
    }, {
      name: '系统公告',
      icon: '',
      path: ''
    }, {
      name: '站内信息',
      icon: '',
      path: ''
    }, {
      name: '客户留言',
      icon: '',
      path: ''
    }, {
      name: '客户评价',
      icon: '',
      path: ''
    }, {
      name: '代办事项',
      icon: '',
      path: ''
    }, {
      name: '消息推送',
      icon: '',
      path: ''
    }, {
      name: '指挥管控',
      icon: '',
      path: ''
    }, {
      name: '运营报告',
      icon: '',
      path: ''
    }]
  }, {
    name: '用户运营',
    icon: '',
    path: '',
    children: [{
      name: '用户管理',
      icon: '',
      path: ''
    }, {
      name: '用户增长',
      icon: '',
      path: ''
    }, {
      name: '用户留存',
      icon: '',
      path: ''
    }, {
      name: '用户社群',
      icon: '',
      path: ''
    }, {
      name: '用户转化',
      icon: '',
      path: ''
    }, {
      name: '用户沟通',
      icon: '',
      path: ''
    }]
  }, {
    name: '产品运营',
    icon: '',
    path: '',
    children: [{
      name: '产品体验',
      icon: '',
      path: ''
    }, {
      name: '产品评价',
      icon: '',
      path: ''
    }, {
      name: '产品反馈',
      icon: '',
      path: ''
    }, {
      name: '产品体系',
      icon: '',
      path: ''
    }]
  }, {
    name: '内容运营',
    icon: '',
    path: '',
    children: [{
      name: '文章素材',
      icon: '',
      path: ''
    }, {
      name: '视频素材',
      icon: '',
      path: ''
    }, {
      name: '业务知识',
      icon: '',
      path: ''
    }]
  }, {
    name: '媒体运营',
    icon: '',
    path: '',
    children: [{
      name: '媒体管理',
      icon: '',
      path: ''
    }, {
      name: '内容分发',
      icon: '',
      path: ''
    }, {
      name: '媒体数据',
      icon: '',
      path: ''
    }]
  }, {
    name: '社区运营',
    icon: '',
    path: '',
    children: [{
      name: '创建社区',
      icon: '',
      path: ''
    }, {
      name: '帖子管理',
      icon: '',
      path: ''
    }, {
      name: '成员管理',
      icon: '',
      path: ''
    }, {
      name: '发布帖子',
      icon: '',
      path: ''
    }]
  }, {
    name: '店铺运营',
    icon: '',
    path: '',
    children: [{
      name: '店铺管理',
      icon: '',
      path: '/storeList'
    }, {
      name: '店铺设置',
      icon: '',
      path: ''
    }, {
      name: '店铺装修',
      icon: '',
      path: ''
    }]
  }, {
    name: '数据运营',
    icon: '',
    path: '',
    children: [{
      name: '官网访客',
      icon: '',
      path: ''
    }, {
      name: '统计报表',
      icon: '',
      path: ''
    }, {
      name: '媒体互动',
      icon: '',
      path: ''
    }]
  }, {
    name: '推广优化',
    icon: '',
    path: '',
    children: [{
      name: '关键词排名',
      icon: '',
      path: ''
    }, {
      name: '优化检测',
      icon: '',
      path: ''
    }, {
      name: 'SEO设置',
      icon: '',
      path: ''
    }, {
      name: '内容SEO',
      icon: '',
      path: ''
    }, {
      name: '排名统计',
      icon: '',
      path: ''
    }]
  }, {
    name: '团队运营',
    icon: '',
    path: '',
    children: [{
      name: '团队设置',
      icon: '',
      path: ''
    }, {
      name: '团队互动',
      icon: '',
      path: ''
    }, {
      name: '团队社区',
      icon: '',
      path: ''
    }, {
      name: '团队活动',
      icon: '',
      path: ''
    }, {
      name: '团队文化',
      icon: '',
      path: ''
    }]
  }]
}, {
  name: '生产',
  icon: '',
  id: 8,
  width: 170,
  children: [{
    name: '产品生产作业流程管理',
    icon: '',
    path: ''
  }, {
    name: '设备管理',
    icon: '',
    path: ''
  }, {
    name: '餐饮行业的厨房生产管理',
    icon: '',
    path: ''
  }, {
    name: '收银台管理',
    icon: '',
    path: ''
  }, {
    name: '自动售货机管理',
    icon: '',
    path: ''
  }, {
    name: '点餐宝管理等终端设备管理',
    icon: '',
    path: ''
  }, {
    name: '文化行业的舞蹈编排',
    icon: '',
    path: ''
  }, {
    name: '演出管理',
    icon: '',
    path: ''
  }, {
    name: '装饰公司的工程作业管理',
    icon: '',
    path: ''
  }, {
    name: '流程管理',
    icon: '',
    path: ''
  }]
}, {
  name: '管理',
  icon: '',
  id: 9,
  width: 130,
  children: [{
    name: '设备管理',
    icon: '',
    path: '/report/main'
  }, {
    name: '收银管理',
    icon: '',
    path: '/checkstand'
  }, {
    name: '财务管理',
    icon: '',
    path: '',
    children: [{
      name: '财务概况',
      icon: '',
      path: '/payment'
    }]
  }, {
    name: '资产管理',
    icon: '',
    path: ''
  }, {
    name: '部门管理',
    icon: '',
    path: ''
  }, {
    name: '员工管理',
    icon: '',
    path: '',
    children: [{
      name: '员工列表',
      icon: '',
      path: ''
    }, {
      name: '组别管理',
      icon: '',
      path: ''
    }, {
      name: '员工打赏',
      icon: '',
      path: ''
    }]
  }, {
    name: '员工提成',
    icon: '',
    path: '',
    children: [{
      name: '商品销售提成',
      icon: '',
      path: ''
    }, {
      name: '会员充值提成',
      icon: '',
      path: ''
    }, {
      name: '推广办卡提成',
      icon: '',
      path: ''
    }, {
      name: '消费订单提成',
      icon: '',
      path: ''
    }, {
      name: '提成报表',
      icon: '',
      path: ''
    }]
  }, {
    name: '门店管理',
    icon: '',
    path: '',
    children: [{
      name: '门店列表',
      icon: '',
      path: ''
    }, {
      name: '新增门店',
      icon: '',
      path: ''
    }, {
      name: '门店排行',
      icon: '',
      path: ''
    }]
  }, {
    name: '权限管理',
    icon: '',
    path: ''
  }, {
    name: '人资管理',
    icon: '',
    path: ''
  }, {
    name: '物资管理',
    icon: '',
    path: ''
  }]
}, {
  name: '生态',
  icon: '',
  id: 10,
  width: 80,
  children: [{
    name: '通证管理',
    icon: '',
    path: '/throughTheManagement/throughTheManagement'
  }, {
    name: '应用中心',
    icon: '',
    path: ''
  }, {
    name: '应用市场',
    icon: '',
    path: ''
  }, {
    name: '我的应用',
    icon: '',
    path: '',
    children: [{
      name: '我的应用',
      icon: '',
      path: ''
    }, {
      name: '订购记录',
      icon: '',
      path: ''
    }]
  }, {
    name: '服务市场',
    icon: '',
    path: ''
  }, {
    name: '人才市场',
    icon: '',
    path: ''
  }, {
    name: '行业媒体',
    icon: '',
    path: ''
  }, {
    name: '行业联盟',
    icon: '',
    path: ''
  }, {
    name: '行业社群',
    icon: '',
    path: ''
  }, {
    name: '行业培训',
    icon: '',
    path: ''
  }, {
    name: '管理咨询',
    icon: '',
    path: ''
  }, {
    name: '行业活动',
    icon: '',
    path: ''
  }]
}]
