export default [{
  // 零售后台 菜单
  path: '/survey',
  name: 'settlement',
  text: '智慧零售',
  icon: 'gongzuotai',
  parent: true,
  component: '',
  children: [
    {
      path: '/survey',
      name: 'survey',
      text: '概况',
      component: '',
      icon: 'el-icon-menu'
    },
    {
      path: '/shop',
      text: '店铺',
      name: 'shop',
      icon: 'el-icon-collection',
      children: [{
        path: '/storeList',
        text: '店铺页面',
        name: 'shop',
        icon: 'el-icon-film',
      }, {
        path: '/error',
        text: '店铺导航',
        name: 'error',
        icon: 'el-icon-film',
      }, {
        path: '/error',
        text: '用户中心',
        name: 'error',
        icon: 'el-icon-user',
      }, {
        path: '/error',
        text: '列表模块',
        name: 'error',
        icon: 'el-icon-user',
      }, {
        path: '/error',
        text: '分类模版',
        name: 'error',
        icon: 'el-icon-user',
      }, {
        path: '/error',
        text: '搜索页',
        name: 'error',
        icon: 'el-icon-user',
      }, {
        path: '/error',
        text: '店铺色系',
        name: 'error',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '商品',
      name: 'shop',
      icon: 'el-icon-magic-stick',
      children: [{
        path: '/listOfUnit',
        text: '单品库列表',
        name: 'listOfUnit',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/Classification',
        text: '单品库分类',
        name: 'Classification',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/shopList',
        text: '商品库列表',
        name: 'shopList',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/commodityGrouping',
        text: '商品分组',
        name: 'commodityGrouping',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/productLabel',
        text: '商品标签',
        name: 'productLabel',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/detailedTemplate',
        text: '商详模板',
        name: 'detailedTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/commodityAttributes',
        text: '商品属性',
        name: 'commodityAttributes',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/profileTemplate',
        text: '档案模板',
        name: 'profileTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/productList',
        text: '商品列表',
        name: 'productList',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/productReviews',
        text: '商品评论',
        name: 'productReviews',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/error',
        text: '供货中心',
        name: 'error',
        icon: 'el-icon-news',
      }]
    },
    {
      path: '/shop',
      text: '库存',
      name: 'shop',
      icon: 'el-icon-s-goods',
      children: [{
        path: '/storeInventory',
        text: '门店库存',
        name: 'storeInventory',
        icon: 'el-icon-s-cooperation',
      }, {
        path: '/inOutDetails',
        text: '出入库明细',
        name: 'inOutDetails',
        icon: 'el-icon-s-cooperation',
      }, {
        path: '/inReceipt',
        text: '入库单',
        name: 'inReceipt',
        icon: 'el-icon-s-cooperation',
      }, {
        path: '/outReceipt',
        text: '出库单',
        name: 'outReceipt',
        icon: 'el-icon-s-cooperation',
      }, {
        path: '/lnventoryChecking',
        text: '库存盘点',
        name: 'lnventoryChecking',
        icon: 'el-icon-s-cooperation',
      }, {
        path: '/inventoryChecking',
        text: '库存控制',
        name: 'inventoryChecking',
        icon: 'el-icon-s-cooperation',
      }, { //--
        path: '/InventorySearch',
        text: '库存查询',
        name: 'InventorySearch',
        icon: 'el-icon-search',
      }, { // --
        path: '/shippingReport',
        text: '出货报告',
        name: 'shippingReport',
        icon: 'el-icon-partly-cloudy',
      }, {
        path: '/shippingIn',
        text: '进货报告',
        name: 'shippingIn',
        icon: 'el-icon-partly-cloudy',
      }, { // --
        path: '/setting',
        text: '供应商管理',
        name: 'setting',
        icon: 'el-icon-setting',
      }]
    },
    {
      path: '/shop',
      text: '门店',
      name: 'shop',
      icon: 'el-icon-shopping-cart-1',
      children: [{
        path: '/storeList',
        text: '门店列表',
        name: 'storeList',
        icon: 'el-icon-sell',
      }, {
        path: '/performanceSetting',
        text: '业绩设置',
        name: 'performanceSetting',
        icon: 'el-icon-sell',
      }, {
        path: '/performanceDetails',
        text: '业绩明细',
        name: 'performanceDetails',
        icon: 'el-icon-sell',
      }, {
        path: '/entryRules',
        text: '进店规则',
        name: 'entryRules',
        icon: 'el-icon-sell',
      }, {///-----
        path: '/regionalManagement',
        text: '区域管理',
        name: 'regionalManagement',
        icon: 'el-icon-present',
      }, {// ---
        path: '/shoppingManagement',
        text: '导购管理',
        name: 'shoppingManagement',
        icon: 'el-icon-box',
      }, {
        path: '/error',
        text: '导购设置',
        name: 'shoppingSetting',
        icon: 'el-icon-box',
      }, {
        path: '/statisticalReport',
        text: '统计报表',
        name: 'statisticalReport',
        icon: 'el-icon-box',
      }, {// ---
        path: '/setup',
        text: '交易设置',
        name: 'setup',
        icon: 'el-icon-bank-card',
      }, {
        path: '/ticketSetting',
        text: '小票设置',
        name: 'ticketSetting',
        icon: 'el-icon-bank-card',
      }, {
        path: '/cashRegister',
        text: '收银台交班',
        name: 'cashRegister',
        icon: 'el-icon-bank-card',
      }]
    },
    {
      path: '/shop',
      text: '订单',
      name: 'shop',
      icon: 'el-icon-box',
      children: [{
        path: '/allOrders',
        text: '全部订单',
        name: 'allOrders',
        icon: 'el-icon-sell',
      }, {
        path: '/recharge0rder',
        text: '充值订单',
        name: 'recharge0rder',
        icon: 'el-icon-sell',
      }, {
        path: '/consumerOrder',
        text: '消费订单',
        name: 'consumerOrder',
        icon: 'el-icon-sell',
      }, {
        path: '/delivery',
        text: '发货管理',
        name: 'delivery',
        icon: 'el-icon-sell',
      }, {///-----
        path: '/selfRaised',
        text: '自提管理',
        name: 'selfRaised',
        icon: 'el-icon-present',
      }, {// ---
        path: '/toBeAllocated',
        text: '待分配订单',
        name: 'toBeAllocated',
        icon: 'el-icon-box',
      }, {
        path: '/communityOrder',
        text: '社区订单管理',
        name: 'communityOrder',
        icon: 'el-icon-box',
      }, {
        path: '/distributionSupply',
        text: '分销供货订单',
        name: 'distributionSupply',
        icon: 'el-icon-box',
      }, {// ---
        path: '/afterSale',
        text: '售后订单',
        name: 'afterSale',
        icon: 'el-icon-bank-card',
      }, {
        path: '/paymentOrderQuery',
        text: '支付单查询',
        name: 'paymentOrderQuery',
        icon: 'el-icon-bank-card',
      }, {
        path: '/cashRegister',
        text: '历史订单',
        name: 'cashRegister',
        icon: 'el-icon-bank-card',
      }, {
        path: '/cashRegister',
        text: '店铺合并',
        name: 'cashRegister',
        icon: 'el-icon-bank-card',
      }]
    },
    {
      path: '/shop',
      text: '客户',
      name: 'shop',
      icon: 'el-icon-magic-stick',
      children: [{
        path: '/allCustoms',
        text: '全部客户',
        name: 'allCustoms',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/customerTag',
        text: '客户标签',
        name: 'customerTag',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/customerSetting',
        text: '客户设置',
        name: 'customerSetting',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/commodityGrouping',
        text: '客户分群',
        name: 'commodityGrouping',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/productLabel',
        text: '黑名单管理',
        name: 'productLabel',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/detailedTemplate',
        text: '会员设置',
        name: 'detailedTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/commodityAttributes',
        text: '会员权益',
        name: 'commodityAttributes',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/profileTemplate',
        text: '积分管理',
        name: 'profileTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/productList',
        text: '储值管理',
        name: 'productList',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '营销',
      name: 'shop',
      icon: 'el-icon-sell ',
      children: [{
        path: '/marketingCenter',
        text: '营销中心',
        name: 'marketingCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/promotionCenter',
        text: '推广中心',
        name: 'promotionCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/advertisingPromotion',
        text: '渠道追踪',
        name: 'advertisingPromotion',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/error',
        text: '全部服务',
        name: 'error',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/myApp',
        text: '我的应用',
        name: 'myApp',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/myOrder',
        text: '我的订单',
        name: 'myOrder',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/commodityAttributes',
        text: '开发者中心',
        name: 'commodityAttributes',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/price',
        text: '开发指南 ',
        // name: 'profileTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/price',
        text: 'API指南',
        // name: 'productList',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '慧付',
      name: 'shop',
      icon: 'el-icon-cpu',
      children: [{
        path: '/payment',
        text: '支付账号',
        name: 'payment',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/collection',
        text: '收款配置',
        name: 'collection',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/paymentColl',
        text: '付款配置',
        name: 'paymentColl',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/offlinePayment',
        text: '线下收款',
        name: 'offlinePayment',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/revenueProfile',
        text: '营收概况',
        name: 'revenueProfile',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/financialDetails',
        text: '财务明细',
        name: 'financialDetails',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/smartRetail',
        text: '线上交易',
        name: 'smartRetail',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/onlineRefund',
        text: '线上退款 ',
        name: 'onlineRefund',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/reconciliationStatement',
        text: '对账报表',
        name: 'reconciliationStatement',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/businessSub',
        text: '业务分账',
        name: 'businessSub',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/accountSplitting',
        text: '线上分账',
        name: 'accountSplitting',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/separateAccount',
        text: '分账解冻',
        name: 'separateAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/billsPayable',
        text: '应付账单',
        name: 'billsPayable',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/withdrawal',
        text: '提现管理',
        name: 'withdrawal',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/paymentRecords',
        text: '付款记录',
        name: 'paymentRecords',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/liveAccounts',
        text: '直播应收',
        name: 'liveAccounts',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/splitOrder',
        text: '分账订单',
        name: 'splitOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/logisticsExpenses',
        text: '三方物流',
        name: 'logisticsExpenses',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/creditDetails',
        text: '积分明细',
        name: 'creditDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/balanceDetails',
        text: '余额明细',
        name: 'balanceDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/rewardSubsidiary',
        text: '微客奖励',
        name: 'rewardSubsidiary',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/communityGroup',
        text: '社区团购',
        name: 'communityGroup',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/electronicInvoice',
        text: '电票配置',
        name: 'electronicInvoice',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/orderFlow',
        text: '电票订单',
        name: 'orderFlow',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/invoiceFinance',
        text: '发票管理',
        name: 'invoiceFinance',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/myAccount',
        text: '我的账户',
        name: 'myAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/withdrawalOrder',
        text: '提现订单',
        name: 'withdrawalOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/balanceReconciliation',
        text: '余额对账',
        name: 'balanceReconciliation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/theInvoicenformation',
        text: '发票管理',
        name: 'theInvoicenformation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/exportManagement',
        text: '导出管理',
        name: 'exportManagement',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '渠道',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/customMenu',
        text: '自定义菜单',
        name: 'customMenu',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/autoReply',
        text: '自动回复',
        name: 'autoReply',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/publicAccount',
        text: '公众号管理',
        name: 'publicAccount',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/appletSetup',
        text: '微信小程序',
        name: 'appletSetup',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/h5Set',
        text: 'H5设置',
        name: 'h5Set',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/APPstore',
        text: 'APP开店',
        name: 'APPstore',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/enterpriseWeChat',
        text: '企业微信',
        name: 'enterpriseWeChat',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '设置',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/businessInformation',
        text: '商户信息',
        name: 'businessInformation',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/shopCertification',
        text: '商户认证',
        name: 'shopCertification',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/storeSettings',
        text: '网店设置',
        name: 'storeSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/goodsSet',
        text: '商品设置',
        name: 'goodsSet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/orderISaet',
        text: '订单设置',
        name: 'orderISaet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/shippingSettings',
        text: '配送设置',
        name: 'shippingSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/theRaskList',
        text: '任务列表',
        name: 'theRaskList',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/error',
        text: '消息通知',
        name: 'error',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/accountAccess',
        text: '账号权限',
        name: 'accountAccess',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/operationLog',
        text: '操作日志',
        name: 'operationLog',
        icon: 'el-icon-notebook-2',
      }]
    }
  ]
}, {
  // 餐厅后台 菜单
  path: '/r_survey',
  name: 'wisdomRestaurant',
  icon: 'gongzuotai',
  text: '智慧餐厅',
  component: '',
  parent: true,
  children: [
    {
      path: '/r_survey',
      name: 'r_survey',
      text: '概况',
      component: '',
      icon: 'el-icon-menu'
    },
    {
      path: '/shop',
      text: '门店',
      name: 'shop',
      icon: 'el-icon-collection',
      children: [{
        path: '/r_storeList',
        text: '门店列表',
        name: 'r_storeList',
        icon: 'el-icon-film',
      }, {
        path: '/r_storeTheTag',
        text: '门店标签',
        name: 'r_storeTheTag',
        icon: 'el-icon-film',
      }, {
        path: '/r_storeArea',
        text: '门店区域',
        name: 'r_storeArea',
        icon: 'el-icon-user',
      }, {
        path: '/r_storesGroup',
        text: '门店分组',
        name: 'r_storesGroup',
        icon: 'el-icon-user',
      }, {
        path: '/r_storeStting',
        text: '门店储值',
        name: 'r_storeStting',
        icon: 'el-icon-user',
      }, {
        path: '/r_valueAndPay',
        text: '储值并买单',
        name: 'r_valueAndPay',
        icon: 'el-icon-user',
      }, {
        path: '/r_thePrinter',
        text: '打印机',
        name: 'r_thePrinter',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_POS',
        text: 'POS',
        name: 'r_POS',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '首页装修',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '导航装修',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '列表装修',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '用户中心',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '业务',
      name: 'shop',
      icon: 'el-icon-mobile',
      children: [{
        path: '/r_checkPayment',
        text: '买单收款',
        name: 'r_checkPayment',
        icon: 'el-icon-film',
      }, {
        path: '/r_stockCenter',
        text: '领券中心',
        name: 'r_stockCenter',
        icon: 'el-icon-film',
      }, {
        path: '/r_APPcollection',
        text: 'APP收款',
        name: 'r_APPcollection',
        icon: 'el-icon-user',
      }, {
        path: '/r_menuManagement',
        text: '菜单管理_食堂',
        name: 'r_menuManagement',
        icon: 'el-icon-user',
      }, {
        path: '/r_basicSetup',
        text: '基本设置_食堂',
        name: 'r_basicSetup',
        icon: 'el-icon-user',
      }, {
        path: '/r_error',
        text: '菜品仓库_食堂',
        name: 'r_error',
        icon: 'el-icon-user',
      }, {
        path: '/r_tablesManagement',
        text: '桌台管理',
        name: 'r_tablesManagement',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '优惠规则',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_staffManagement',
        text: '菜单管理_外卖',
        name: 'r_staffManagement',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_basicSetupT',
        text: '基本设置_外卖',
        name: 'r_basicSetupT',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '菜品仓库_外卖',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '优惠规则',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_staffManagementa',
        text: '员工管理',
        name: 'r_staffManagementa',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_marketingStaff',
        text: '员工营销',
        name: 'r_marketingStaff',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '订单',
      name: 'shop',
      icon: 'el-icon-umbrella',
      children: [{
        path: '/r_checkPayments',
        text: '买单收款',
        name: 'r_checkPayments',
        icon: 'el-icon-film',
      }, {
        path: '/r_posReceipt',
        text: 'POS收款',
        name: 'r_posReceipt',
        icon: 'el-icon-film',
      }, {
        path: '/r_addedTrading',
        text: '补充交易',
        name: 'r_addedTrading',
        icon: 'el-icon-user',
      }, {
        path: '/r_appPayment',
        text: 'APP收款',
        name: 'r_appPayment',
        icon: 'el-icon-user',
      }, {
        path: '/r_eatIn',
        text: '堂食',
        name: 'r_eatIn',
        icon: 'el-icon-user',
      }, {
        path: '/r_secondsToPay',
        text: '秒付',
        name: 'r_secondsToPay',
        icon: 'el-icon-user',
      }, {
        path: '/r_takeOut',
        text: '外卖',
        name: 'r_takeOut',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_reservation',
        text: '预订',
        name: 'r_reservation',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_lntegralMall',
        text: '积分商城',
        name: 'r_lntegralMall',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_partyOrder',
        text: '第三方订单',
        name: 'r_partyOrder',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_orderManagement',
        text: '会员开卡',
        name: 'r_orderManagement',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_valueOrder',
        text: '会员储值订单',
        name: 'r_valueOrder',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_storageCard',
        text: '门店储值订单',
        name: 'r_storageCard',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_orderManage',
        text: '券订单',
        name: 'r_orderManage',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_orderExport',
        text: '订单导出',
        name: 'r_orderExport',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '会员',
      name: 'shop',
      icon: 'el-icon-refrigerator',
      children: [{
        path: '/r_userList',
        text: '用户列表',
        name: 'r_userList',
        icon: 'el-icon-film',
      }, {
        path: '/r_newcardview',
        text: '会员卡设置',
        name: 'r_newcardview',
        icon: 'el-icon-film',
      }, {
        path: '/r_levelManage',
        text: '等级设置',
        name: 'r_levelManage',
        icon: 'el-icon-user',
      }, {
        path: '/r_upgrade',
        text: '升级规则',
        name: 'r_upgrade',
        icon: 'el-icon-user',
      }, {
        path: '/r_tagsManage',
        text: '标签管理',
        name: 'r_tagsManage',
        icon: 'el-icon-user',
      }, {
        path: '/r_IntegralRules',
        text: '积分规则',
        name: 'r_IntegralRules',
        icon: 'el-icon-user',
      }, {
        path: '/r_integralStrategy',
        text: '积分活动',
        name: 'r_integralStrategy',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_error',
        text: '商品管理',
        name: 'r_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_storedValueRules',
        text: '储值规则',
        name: 'r_storedValueRules',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/r_balanceStatement',
        text: '余额流水',
        name: 'r_balanceStatement',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '营销',
      name: 'shop',
      icon: 'el-icon-sell ',
      children: [{
        path: '/r_marketingCenter',
        text: '营销中心',
        name: 'r_marketingCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_error',
        text: '开发者中心',
        name: 'r_error',
        icon: 'el-icon-data-analysis',
      }]
    },
    {
      path: '/r_toPromote',
      text: '推广',
      name: 'r_toPromote',
      icon: 'el-icon-sell ',
    },
    {
      path: '/r_shop',
      text: '慧付',
      name: 'shop',
      icon: 'el-icon-cpu',
      children: [{
        path: '/r_payment',
        text: '支付账号',
        name: 'r_payment',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_collection',
        text: '收款配置',
        name: 'r_collection',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_paymentColl',
        text: '付款配置',
        name: 'r_paymentColl',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_offlinePayment',
        text: '线下收款',
        name: 'r_offlinePayment',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_revenueProfile',
        text: '营收概况',
        name: 'r_revenueProfile',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_financialDetails',
        text: '财务明细',
        name: 'r_financialDetails',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_smartRetail',
        text: '线上交易',
        name: 'r_smartRetail',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_onlineRefund',
        text: '线上退款 ',
        name: 'r_onlineRefund',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_reconciliationStatement',
        text: '对账报表',
        name: 'r_reconciliationStatement',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_businessSub',
        text: '业务分账',
        name: 'r_businessSub',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_accountSplitting',
        text: '线上分账',
        name: 'r_accountSplitting',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_separateAccount',
        text: '分账解冻',
        name: 'r_separateAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_billsPayable',
        text: '应付账单',
        name: 'r_billsPayable',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_withdrawal',
        text: '提现管理',
        name: 'r_withdrawal',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_paymentRecords',
        text: '付款记录',
        name: 'r_paymentRecords',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_liveAccounts',
        text: '直播应收',
        name: 'r_liveAccounts',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_splitOrder',
        text: '分账订单',
        name: 'r_splitOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_logisticsExpenses',
        text: '三方物流',
        name: 'r_logisticsExpenses',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_creditDetails',
        text: '积分明细',
        name: 'r_creditDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_balanceDetails',
        text: '余额明细',
        name: 'r_balanceDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_rewardSubsidiary',
        text: '微客奖励',
        name: 'r_rewardSubsidiary',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_communityGroup',
        text: '社区团购',
        name: 'r_communityGroup',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_electronicInvoice',
        text: '电票配置',
        name: 'r_electronicInvoice',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_orderFlow',
        text: '电票订单',
        name: 'r_orderFlow',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_invoiceFinance',
        text: '发票管理',
        name: 'r_invoiceFinance',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_myAccount',
        text: '我的账户',
        name: 'r_myAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_withdrawalOrder',
        text: '提现订单',
        name: 'r_withdrawalOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_balanceReconciliation',
        text: '余额对账',
        name: 'r_balanceReconciliation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_theInvoicenformation',
        text: '发票管理',
        name: 'r_theInvoicenformation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/r_exportManagement',
        text: '导出管理',
        name: 'r_exportManagement',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '渠道',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/r_publicAccount',
        text: '公众号授权管理',
        name: 'r_publicAccount',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_customMenu',
        text: '自定义菜单',
        name: 'r_customMenu',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_autoReply',
        text: '自动回复',
        name: 'r_autoReply',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_appletSetup',
        text: '微信小程序授权管理',
        name: 'r_appletSetup',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '设置',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/r_businessInformation',
        text: '商户信息',
        name: 'r_businessInformation',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_shopCertification',
        text: '商户认证',
        name: 'r_shopCertification',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/r_storeSettings',
        text: '网店设置',
        name: 'r_storeSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_goodsSet',
        text: '商品设置',
        name: 'r_goodsSet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_orderISaet',
        text: '订单设置',
        name: 'r_orderISaet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_shippingSettings',
        text: '配送设置',
        name: 'r_shippingSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_theRaskList',
        text: '任务列表',
        name: 'r_theRaskList',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_error',
        text: '消息通知',
        name: 'r_error',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_accountAccess',
        text: '账号权限',
        name: 'r_accountAccess',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/r_operationLog',
        text: '操作日志',
        name: 'r_operationLog',
        icon: 'el-icon-notebook-2',
      }]
    }
  ]
}, {
  //旅游后台 菜单
  path: '/o_survey',
  name: 'ofTourism',
  icon: 'gongzuotai',
  text: '智慧旅游',
  component: '',
  parent: true,
  children: [
    {
      path: '/o_survey',
      name: 'o_survey',
      text: '概况',
      component: '',
      icon: 'el-icon-menu'
    },
    {
      path: '/shop',
      text: '店铺',
      name: 'shop',
      icon: 'el-icon-collection',
      children: [{
        path: '/o_storeList',
        text: '店铺页面',
        name: 'o_storeList',
        icon: 'el-icon-film',
      }, {
        path: '/o_error',
        text: '店铺导航',
        name: 'o_error',
        icon: 'el-icon-film',
      }, {
        path: '/o_error',
        text: '分类模版',
        name: 'o_error',
        icon: 'el-icon-user',
      }]
    },
    {
      path: '/shop',
      text: '产品',
      name: 'shop',
      icon: 'el-icon-s-help',
      children: [
        {
          path: '/o_lineList',
          text: '线路列表',
          name: 'o_lineList',
          icon: 'el-icon-film',
        }, {
          path: '/o_lineOrder',
          text: '线路订单',
          name: 'o_lineOrder',
          icon: 'el-icon-film',
        }, {
          path: '/o_lineActivist',
          text: '线路维权',
          name: 'o_lineActivist',
          icon: 'el-icon-user',
        }, {
          path: '/o_lineSetUp',
          text: '线路设置',
          name: 'o_lineSetUp',
          icon: 'el-icon-film',
        }, {
          path: '/o_listOfAttractions',
          text: '景点列表',
          name: 'o_listOfAttractions',
          icon: 'el-icon-film',
        }, {
          path: '/o_tickets',
          text: '门票订单',
          name: 'o_tickets',
          icon: 'el-icon-user',
        }, {
          path: '/o_verification',
          text: '门票核销',
          name: 'o_verification',
          icon: 'el-icon-film',
        }, {
          path: '/o_theRights',
          text: '门票维权',
          name: 'o_theRights',
          icon: 'el-icon-film',
        }, {
          path: '/o_setOfTickets',
          text: '门票设置',
          name: 'o_setOfTickets',
          icon: 'el-icon-film',
        }, {
          path: '/o_lnsuranceProducts',
          text: '保险产品',
          name: 'o_lnsuranceProducts',
          icon: 'el-icon-user',
        }, {
          path: '/o_ofGoods',
          text: '商品分类',
          name: 'o_ofGoods',
          icon: 'el-icon-film',
        }, {
          path: '/o_additionalProduct',
          text: '附加产品',
          name: 'o_additionalProduct',
          icon: 'el-icon-film',
        }]
    },
    {
      path: '/shop',
      text: '会员',
      name: 'shop',
      icon: 'el-icon-brush',
      children: [{
        path: '/o_error',
        text: '会员列表',
        name: 'o_error',
        icon: 'el-icon-film',
      }, {
        path: '/o_theTagList',
        text: '标签列表',
        name: 'o_theTagList',
        icon: 'el-icon-film',
      }, {
        path: '/o_membersM',
        text: '会员卡管理',
        name: 'o_membersM',
        icon: 'el-icon-user',
      }]
    },
    {
      path: '/shop',
      text: '营销',
      name: 'shop',
      icon: 'el-icon-sell ',
      children: [{
        path: '/o_marketingCenter',
        text: '营销中心',
        name: 'o_marketingCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_promotionCenter',
        text: '推广中心',
        name: 'o_promotionCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_advertisingPromotion',
        text: '渠道追踪',
        name: 'o_advertisingPromotion',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_error',
        text: '全部服务',
        name: 'o_error',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_myApp',
        text: '我的应用',
        name: 'o_myApp',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_myOrder',
        text: '我的订单',
        name: 'o_myOrder',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_commodityAttributes',
        text: '开发者中心',
        name: 'o_commodityAttributes',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/price',
        text: '开发指南 ',
        // name: 'profileTemplate',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/price',
        text: 'API指南',
        // name: 'productList',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '微信',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/o_publicAccount',
        text: '公众号授权管理',
        name: 'o_publicAccount',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_customMenu',
        text: '自定义菜单',
        name: 'o_customMenu',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_autoReply',
        text: '自动回复',
        name: 'o_autoReply',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_appletSetup',
        text: '小程序设置',
        name: 'o_appletSetup',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '数据',
      name: 'shop',
      icon: 'el-icon-s-shop',
      children: [{
        path: '/o_error',
        text: '店铺统计',
        name: 'o_error',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_downloadCenter',
        text: '下载中心',
        name: 'o_downloadCenter',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_ImportCenter',
        text: '导入中心',
        name: 'o_ImportCenter',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '设置',
      name: 'shop',
      icon: 'el-icon-s-tools',
      children: [{
        path: '/o_businessInformation',
        text: '商户信息',
        name: 'o_businessInformation',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_shopCertification',
        text: '资质认证',
        name: 'o_shopCertification',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_accountAccess',
        text: '账号',
        name: 'o_accountAccess',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_characterSet',
        text: '角色管理',
        name: 'o_characterSet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_operationLog',
        text: '操作日志',
        name: 'o_operationLog',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_error',
        text: '模版消息',
        name: 'o_error',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '供应商',
      name: 'shop',
      icon: 'el-icon-bank-card',
      children: [{
        path: '/o_supplierList',
        text: '供应商列表',
        name: 'o_supplierList',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_supplierData',
        text: '供应商数据',
        name: 'o_supplierData',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/o_shop',
      text: '慧付',
      name: 'shop',
      icon: 'el-icon-cpu',
      children: [{
        path: '/o_payment',
        text: '支付账号',
        name: 'o_payment',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_collection',
        text: '收款配置',
        name: 'o_collection',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/o_paymentColl',
        text: '付款配置',
        name: 'o_paymentColl',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_smartRetail',
        text: '线上交易',
        name: 'o_smartRetail',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_onlineRefund',
        text: '线上退款 ',
        name: 'o_onlineRefund',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/o_reconciliationStatement',
        text: '对账报表',
        name: 'o_reconciliationStatement',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_businessSub',
        text: '业务分账',
        name: 'o_businessSub',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_accountSplitting',
        text: '线上分账',
        name: 'o_accountSplitting',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_separateAccount',
        text: '分账解冻',
        name: 'o_separateAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_billsPayable',
        text: '应付账单',
        name: 'o_billsPayable',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_withdrawal',
        text: '提现管理',
        name: 'o_withdrawal',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_paymentRecords',
        text: '付款记录',
        name: 'o_paymentRecords',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/o_exportManagement',
        text: '导出管理',
        name: 'o_exportManagement',
        icon: 'el-icon-toilet-paper',
      }]
    },
  ]
}, {
  // 智慧美业 菜单
  path: 'b_survey',
  name: 'beautyIndustry',
  icon: 'gongzuotai',
  text: '智慧美业',
  component: '',
  parent: true,
  children: [
    {
      path: '/b_survey',
      name: 'b_survey',
      text: '概况',
      component: '',
      icon: 'el-icon-menu'
    },
    {
      path: '/shop',
      text: '门店',
      name: 'shop',
      icon: 'el-icon-collection',
      children: [{
        path: '/b_storeList',
        text: '门店列表',
        name: 'b_storeList',
        icon: 'el-icon-film',
      }, {
        path: '/b_storeTheTag',
        text: '门店标签',
        name: 'b_storeTheTag',
        icon: 'el-icon-film',
      }, {
        path: '/b_storeArea',
        text: '门店区域',
        name: 'b_storeArea',
        icon: 'el-icon-user',
      }, {
        path: '/b_storesGroup',
        text: '门店分组',
        name: 'b_storesGroup',
        icon: 'el-icon-user',
      }, {
        path: '/b_storeStting',
        text: '门店储值',
        name: 'b_storeStting',
        icon: 'el-icon-user',
      }, {
        path: '/b_valueAndPay',
        text: '储值并买单',
        name: 'b_valueAndPay',
        icon: 'el-icon-user',
      }, {
        path: '/b_thePrinter',
        text: '打印机',
        name: 'b_thePrinter',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_POS',
        text: 'POS',
        name: 'b_POS',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_error',
        text: '首页装修',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_error',
        text: '导航装修',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_error',
        text: '列表装修',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_error',
        text: '用户中心',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '业务',
      name: 'shop',
      icon: 'el-icon-mobile',
      children: [{
        path: '/b_checkPayment',
        text: '买单收款',
        name: 'b_checkPayment',
        icon: 'el-icon-film',
      }, {
        path: '/b_stockCenter',
        text: '领券中心',
        name: 'b_stockCenter',
        icon: 'el-icon-film',
      }, {
        path: '/b_APPcollection',
        text: 'APP收款',
        name: 'b_APPcollection',
        icon: 'el-icon-user',
      }, {
        path: '/b_serviceManagement',
        text: '服务管理',
        name: 'b_serviceManagement',
        icon: 'el-icon-user',
      }, {
        path: '/b_writeOff',
        text: '售卖及核销',
        name: 'b_writeOff',
        icon: 'el-icon-user',
      }, {
        path: '/b_goodsWarehouse',
        text: '商品仓库',
        name: 'b_goodsWarehouse',
        icon: 'el-icon-user',
      }, {
        path: '/b_error',
        text: '优惠规则',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_buySet',
        text: '购买设置',
        name: 'b_buySet',
        icon: 'el-icon-user',
      }, {
        path: '/b_setAppointmentt',
        text: '预约设置',
        name: 'b_setAppointmentt',
        icon: 'el-icon-user',
      }, {
        path: '/b_staffManagementa',
        text: '员工管理',
        name: 'b_staffManagementa',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_marketingStaff',
        text: '员工营销',
        name: 'b_marketingStaff',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '订单',
      name: 'shop',
      icon: 'el-icon-umbrella',
      children: [{
        path: '/b_checkPayments',
        text: '买单收款',
        name: 'b_checkPayments',
        icon: 'el-icon-film',
      }, {
        path: '/b_posReceipt',
        text: 'POS收款',
        name: 'b_posReceipt',
        icon: 'el-icon-film',
      }, {
        path: '/b_appPayment',
        text: 'APP收款',
        name: 'b_appPayment',
        icon: 'el-icon-user',
      }, {
        path: '/b_lntegralMall',
        text: '积分商城',
        name: 'b_lntegralMall',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_partyOrder',
        text: '服务订单',
        name: 'b_partyOrder',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_orderManagement',
        text: '会员开卡',
        name: 'b_orderManagement',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_valueOrder',
        text: '会员储值订单',
        name: 'b_valueOrder',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_storageCard',
        text: '门店储值订单',
        name: 'b_storageCard',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_orderManage',
        text: '券订单',
        name: 'b_orderManage',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_orderExport',
        text: '订单导出',
        name: 'b_orderExport',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '会员',
      name: 'shop',
      icon: 'el-icon-refrigerator',
      children: [{
        path: '/b_userList',
        text: '用户列表',
        name: 'b_userList',
        icon: 'el-icon-film',
      }, {
        path: '/b_newcardview',
        text: '会员卡设置',
        name: 'b_newcardview',
        icon: 'el-icon-film',
      }, {
        path: '/b_levelManage',
        text: '等级设置',
        name: 'b_levelManage',
        icon: 'el-icon-user',
      }, {
        path: '/b_upgrade',
        text: '升级规则',
        name: 'b_upgrade',
        icon: 'el-icon-user',
      }, {
        path: '/b_tagsManage',
        text: '标签管理',
        name: 'b_tagsManage',
        icon: 'el-icon-user',
      }, {
        path: '/b_IntegralRules',
        text: '积分规则',
        name: 'b_IntegralRules',
        icon: 'el-icon-user',
      }, {
        path: '/b_integralStrategy',
        text: '积分活动',
        name: 'b_integralStrategy',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_error',
        text: '商品管理',
        name: 'b_error',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_storedValueRules',
        text: '储值规则',
        name: 'b_storedValueRules',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/b_balanceStatement',
        text: '余额流水',
        name: 'b_balanceStatement',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '营销',
      name: 'shop',
      icon: 'el-icon-sell ',
      children: [{
        path: '/b_marketingCenter',
        text: '营销中心',
        name: 'b_marketingCenter',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_error',
        text: '开发者中心',
        name: 'b_error',
        icon: 'el-icon-data-analysis',
      }]
    },
    {
      path: '/b_toPromote',
      text: '推广',
      name: 'b_toPromote',
      icon: 'el-icon-sell ',
    },
    {
      path: '/b_shop',
      text: '慧付',
      name: 'shop',
      icon: 'el-icon-cpu',
      children: [{
        path: '/b_payment',
        text: '支付账号',
        name: 'b_payment',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_collection',
        text: '收款配置',
        name: 'b_collection',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_paymentColl',
        text: '付款配置',
        name: 'b_paymentColl',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_offlinePayment',
        text: '线下收款',
        name: 'b_offlinePayment',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_revenueProfile',
        text: '营收概况',
        name: 'b_revenueProfile',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_financialDetails',
        text: '财务明细',
        name: 'b_financialDetails',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_smartRetail',
        text: '线上交易',
        name: 'b_smartRetail',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_onlineRefund',
        text: '线上退款 ',
        name: 'b_onlineRefund',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_reconciliationStatement',
        text: '对账报表',
        name: 'b_reconciliationStatement',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_businessSub',
        text: '业务分账',
        name: 'b_businessSub',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_accountSplitting',
        text: '线上分账',
        name: 'b_accountSplitting',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_separateAccount',
        text: '分账解冻',
        name: 'b_separateAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_billsPayable',
        text: '应付账单',
        name: 'b_billsPayable',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_withdrawal',
        text: '提现管理',
        name: 'b_withdrawal',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_paymentRecords',
        text: '付款记录',
        name: 'b_paymentRecords',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_liveAccounts',
        text: '直播应收',
        name: 'b_liveAccounts',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_splitOrder',
        text: '分账订单',
        name: 'b_splitOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_logisticsExpenses',
        text: '三方物流',
        name: 'b_logisticsExpenses',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_creditDetails',
        text: '积分明细',
        name: 'b_creditDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_balanceDetails',
        text: '余额明细',
        name: 'b_balanceDetails',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_rewardSubsidiary',
        text: '微客奖励',
        name: 'b_rewardSubsidiary',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_communityGroup',
        text: '社区团购',
        name: 'b_communityGroup',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_electronicInvoice',
        text: '电票配置',
        name: 'b_electronicInvoice',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_orderFlow',
        text: '电票订单',
        name: 'b_orderFlow',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_invoiceFinance',
        text: '发票管理',
        name: 'b_invoiceFinance',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_myAccount',
        text: '我的账户',
        name: 'b_myAccount',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_withdrawalOrder',
        text: '提现订单',
        name: 'b_withdrawalOrder',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_balanceReconciliation',
        text: '余额对账',
        name: 'b_balanceReconciliation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_theInvoicenformation',
        text: '发票管理',
        name: 'b_theInvoicenformation',
        icon: 'el-icon-toilet-paper',
      }, {
        path: '/b_exportManagement',
        text: '导出管理',
        name: 'b_exportManagement',
        icon: 'el-icon-toilet-paper',
      }]
    },
    {
      path: '/shop',
      text: '渠道',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/b_publicAccount',
        text: '公众号授权管理',
        name: 'b_publicAccount',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_customMenu',
        text: '自定义菜单',
        name: 'b_customMenu',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_autoReply',
        text: '自动回复',
        name: 'b_autoReply',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_appletSetup',
        text: '微信小程序授权管理',
        name: 'b_appletSetup',
        icon: 'el-icon-notebook-2',
      }]
    },
    {
      path: '/shop',
      text: '设置',
      name: 'shop',
      icon: 'el-icon-sunny ',
      children: [{
        path: '/b_businessInformation',
        text: '商户信息',
        name: 'b_businessInformation',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_shopCertification',
        text: '商户认证',
        name: 'b_shopCertification',
        icon: 'el-icon-data-analysis',
      }, {
        path: '/b_storeSettings',
        text: '网店设置',
        name: 'b_storeSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_goodsSet',
        text: '商品设置',
        name: 'b_goodsSet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_orderISaet',
        text: '订单设置',
        name: 'b_orderISaet',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_shippingSettings',
        text: '配送设置',
        name: 'b_shippingSettings',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_theRaskList',
        text: '任务列表',
        name: 'b_theRaskList',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_error',
        text: '消息通知',
        name: 'b_error',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_accountAccess',
        text: '账号权限',
        name: 'b_accountAccess',
        icon: 'el-icon-notebook-2',
      }, {
        path: '/b_operationLog',
        text: '操作日志',
        name: 'b_operationLog',
        icon: 'el-icon-notebook-2',
      }]
    }
  ]
}, {
  // 智慧美业 菜单
  path: 'h_survey',
  name: 'wisdomHotel',
  icon: 'gongzuotai',
  text: '智慧美业',
  component: '',
  parent: true,
  children: [
    {
      path: '/h_survey',
      name: 'h_survey',
      text: '概况',
      component: '',
      icon: 'el-icon-menu'
    },
    {
      path: '/h_toRoom',
      name: 'h_toRoom',
      text: '房态',
      component: '',
      icon: 'el-icon-s-home'
    },
    {
      path: '/shop',
      text: '订单',
      name: 'shop',
      icon: 'el-icon-mobile',
      children: [{
        path: '/h_bookingOrder',
        text: '订房订单',
        name: 'h_bookingOrder',
        icon: 'el-icon-film',
      }, {
        path: '/h_accommodationRecord',
        text: '住宿记录',
        name: 'h_accommodationRecord',
        icon: 'el-icon-film',
      }, {
        path: '/h_orderRecord',
        text: '订单记录',
        name: 'h_orderRecord',
        icon: 'el-icon-user',
      }, {
        path: '/h_orderList',
        text: '预约订单',
        name: 'h_orderList',
        icon: 'el-icon-user',
      }, {
        path: '/h_verification',
        text: '核销记录',
        name: 'h_verification',
        icon: 'el-icon-user',
      }, {
        path: '/h_eat_inOrders',
        text: '堂食订单',
        name: 'h_eat_inOrders',
        icon: 'el-icon-user',
      }, {
        path: '/h_rightsList',
        text: '售后订单',
        name: 'h_rightsList',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_error',
        text: '售后设置',
        name: 'h_error',
        icon: 'el-icon-user',
      }, {
        path: '/h_refundList',
        text: '押金退款列表',
        name: 'h_refundList',
        icon: 'el-icon-user',
      }, {
        path: '/h_cardOrder',
        text: '会员开卡订单',
        name: 'h_cardOrder',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_collection',
        text: '收款码订单',
        name: 'h_collection',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_qrcode',
        text: '扫码核销',
        name: 'h_qrcode',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_order',
        text: '第三方订单',
        name: 'h_order',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '业务',
      name: 'shop',
      icon: 'el-icon-mobile',
      children: [{
        path: '/h_roomstatus',
        text: '房态维护',
        name: 'h_roomstatus',
        icon: 'el-icon-film',
      }, {
        path: '/h_manage',
        text: '房价管理',
        name: 'h_manage',
        icon: 'el-icon-film',
      }, {
        path: '/h_acSet',
        text: '住宿设置',
        name: 'h_acSet',
        icon: 'el-icon-user',
      }, {
        path: '/h_roomSetting',
        text: '房型设置',
        name: 'h_roomSetting',
        icon: 'el-icon-user',
      }, {
        path: '/h_roomtype',
        text: '房号管理',
        name: 'h_roomtype',
        icon: 'el-icon-user',
      }, {
        path: '/h_goods',
        type: 'list',
        text: '商品列表',
        name: 'h_goods',
        icon: 'el-icon-user',
      }, {
        path: '/h_goods',
        type: 'appointList',
        text: '预约列表',
        name: '/h_goods',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_goods',
        type: 'gatherList',
        text: '聚合商品',
        name: '/h_goods',
        icon: 'el-icon-user',
      }, {
        path: '/h_goods',
        type: 'labelList',
        text: '商品标签',
        name: '/h_goods',
        icon: 'el-icon-user',
      }, {
        path: '/h_catalog',
        text: '分类管理',
        name: 'h_catalog',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_merchant',
        text: '商户管理',
        name: 'h_merchant',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_goods',
        text: '商品设置',
        type: 'setting',
        name: '/h_goods',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_food',
        type: 'list',
        text: '菜品列表',
        name: 'h_food',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_food',
        type: 'group',
        text: '菜品分组',
        name: 'h_food',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_food',
        type: 'standard',
        text: '菜品规格',
        name: 'h_food',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_food',
        type: 'setting',
        text: '堂食设置',
        name: 'h_food',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_tableList',
        text: '桌号管理',
        name: 'h_tableList',
        icon: 'el-icon-takeaway-box',
      }, {
        path: '/h_collection',
        text: '收款码列表',
        name: 'h_collection',
        icon: 'el-icon-takeaway-box',
      }]
    },
    {
      path: '/shop',
      text: '客户',
      name: 'shop',
      icon: 'el-icon-mobile',
      children: [{
        path: '/h_bookingOrder',
        text: '客户列表',
        name: 'h_bookingOrder',
        icon: 'el-icon-film',
      }, {
        path: '/h_accommodationRecord',
        text: '会员卡管理',
        name: 'h_accommodationRecord',
        icon: 'el-icon-film',
      }, {
        path: '/h_orderRecord',
        text: '余额流水',
        name: 'h_orderRecord',
        icon: 'el-icon-user',
      }]
    }
  ]
}]